export enum NamecheapCommand {
	DOMAINS_GET_LIST = 'namecheap.domains.getList',
	CREATE_DOMAIN = 'namecheap.domains.create',
	CHECK_DOMAIN_AVAILABILITY = 'namecheap.domains.check',
	GET_TLD_LIST = 'namecheap.domains.getTldList',
	GET_CONTACTS = 'namecheap.domains.getContacts',
	SET_CONTACTS = 'namecheap.domains.setContacts',
	GET_REGISTRAR_LOCK = 'namecheap.domains.getRegistrarLock',
	SET_REGISTRAR_LOCK = 'namecheap.domains.setRegistrarLock',
	GET_INFO = 'namecheap.domains.getinfo',
	SET_DEFAULT_DNS = 'namecheap.domains.dns.setDefault',
	SET_CUSTOM_DNS = 'namecheap.domains.dns.setCustom',
	GET_DNS_LIST = 'namecheap.domains.dns.getList',
	GET_DNS_HOSTS = 'namecheap.domains.dns.getHosts',
	GET_DNS_EMAIL_FORWARDING = 'namecheap.domains.dns.getEmailForwarding',
	SET_DNS_EMAIL_FORWARDING = 'namecheap.domains.dns.setEmailForwarding',
	NS_CREATE = 'namecheap.domains.ns.create',
	NS_DELETE = 'namecheap.domains.ns.delete',
	NS_GET_INFO = 'namecheap.domains.ns.getInfo',
	NS_UPDATE = 'namecheap.domains.ns.update',
}
